# Generated by Django 5.0.1 on 2024-01-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('bike_license_number', models.CharField(max_length=13)),
                ('bike_brand', models.CharField(choices=[('Hero', 'Hero'), ('KTM', 'KTM'), ('Royal Enfield', 'Royal Enfield')], max_length=50)),
                ('bike_model', models.CharField(choices=[('Xpulse', 'Xpulse (Hero)'), ('Duke 200', 'Duke 200 (KTM)'), ('Continental GT650', 'Continental GT650 (Royal Enfield)')], max_length=50)),
                ('year_of_registration', models.IntegerField(choices=[(2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024')])),
                ('km_driven', models.IntegerField()),
                ('city', models.CharField(choices=[('Palakkad', 'Palakkad'), ('Ernankulam', 'Ernankulam')], max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
