# Generated by Django 5.0.1 on 2024-01-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='bike_brand',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='bike_model',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='city',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='km_driven',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='year_of_registration',
        ),
        migrations.AlterField(
            model_name='owner',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
