# Generated by Django 5.0.1 on 2024-01-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_remove_owner_bike_brand_remove_owner_bike_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='bike_license_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
