# Generated by Django 5.0.1 on 2024-01-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_alter_owner_bike_license_number_alter_owner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
