# Generated by Django 5.0.1 on 2024-04-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_alter_owner_bike_license_number_alter_owner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Email'),
        ),
    ]
