# Generated by Django 5.0.1 on 2024-01-30 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_bikemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=15)),
                ('km_driven', models.PositiveIntegerField()),
                ('year_of_registration', models.PositiveIntegerField()),
                ('city', models.CharField(choices=[('Kasaragod', 'Kasaragod'), ('Kannur', 'Kannur'), ('Wayanad', 'Wayanad'), ('Kozhikode', 'Kozhikode'), ('Palakkad', 'Palakkad'), ('Thrissur', 'Thrissur'), ('Ernakulam', 'Ernakulam'), ('Idukki', 'Idukki'), ('Malappuram', 'Malappuram'), ('Kottayam', 'Kottayam'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kollam', 'Kollam'), ('Alappuzha', 'Alappuzha'), ('Pathanamthitta', 'Pathanamthitta')], max_length=50)),
                ('images', models.ImageField(blank=True, null=True, upload_to='bike_images/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.bikebrand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.bikemodel')),
            ],
        ),
    ]
