# Generated by Django 5.0.1 on 2024-02-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_bike'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='bike_rent',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
