# Generated by Django 5.0.1 on 2024-02-18 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0004_bike_bike_rent'),
        ('owner', '0005_alter_owner_bike_license_number_alter_owner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='owner.owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='owner_name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='owner_phone_number',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
