# Generated by Django 5.0.1 on 2024-03-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0011_alter_booking_bike_alter_booking_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='owner',
            field=models.CharField(max_length=100),
        ),
    ]
